name: Trigger on CareConnect Frontend Changes 



on:
  push:
    branches:
      - master  # Replace with your branch name
    paths:
      - careconnect-front/**

jobs:
  deploy:
    runs-on: self-hosted  
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          cd careconnect-front
          npm install
          npm run build
          
          cp -r ./dist/* /home/nousless/nginx/html/careconnect
          docker restart careconnect
