name: Deploy react-app 



on:
  push:
    branches:
      - master  # Replace with your branch name

jobs:
  deploy:
    runs-on: self-hosted  
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          cd careconnect-front
          npm install
          npm run build
          
          sudo cp -r ./dist/* /home/nousless/nginx/app/careconnect
